### ISSUE TITLE
Unable to send files to Zune 8

### ISSUE THREAD

**Issue by 0rAX0** [kbhomes/libmtp-zune#2]
Hi,

I installed this package instead of libmtp and I'm trying to use programs like gMTP or Rhythmbox to send files to my Zune. With gMTP I'm able to detect, list files and navigate my Zune. But I get "Error getting file from MTP device." when I try to copy them to my computer and fail to create anything on it.

Am I missing something?

**Comment by 0rAX0** [comment]
Sorry, I think it's working now. Missed the mtp-connect part. :P

**Comment by kbhomes** [comment]
Programs like gMTP or others may be linked to earlier versions of libmtp and thus wouldn't have this capability. For certain, you can use the built in examples for libmtp such as mtp-files, mtp-get-file, mtp-sendtr and what have you. We're working on trying to include compatibility for other programs.

Out of curiosity, were you able to successfully transfer files to and from your device?

**Comment by kbhomes** [comment]
Actually, compiling gMTP from source allows one to use it to properly interface with the Zune. If it did correctly, then you should be seeing the "syncing" text on your Zune. Now, you were getting the "Error getting file from MTP device." as was I, but it turns out that in the preferences of gMTP, it defaults to downloading the file into the / directory which it (generally) doesn't have permission for. Changing this to a user-writable directory allows you to download songs correctly.

**Comment by 0rAX0** [comment]
Yes, I was able to transfer files, delete and create directories... with no problem at all, all thanks to you. Well, I read some of your blog posts and found out that it should be displaying the "syncing" screen to be able to read/write. So whenever I want to transfer files, I start mtp-connect from the terminal and gMTP just works automagically(the connect on gMTP doesn't work).

I didn't know I need to recompile, that's probably why Rhythmbox was crashing upon transfer. I will try to compile gMTP and some other media player from source and change the defaults. Thank you for your work. :)

**Comment by kbhomes** [comment]
Ah, that seems like the method used by people before I reverse engineered the protocol. That is, they would open up a Windows virtual machine and run the official Zune software to connect to the device, and then use programs on their host computer to connect to the device thereafter.

Recompiling should allow you to use gMTP on its own without mtp-connect (which is just an example, anyway). And no problem! Hopefully soon enough you'll see these changes merged into the official libmtp branch.

**Comment by 0rAX0** [comment]
Oh, I haven't thought of that one. :P

Unfortunately, gMTP doesn't entry sync-mode automatically. I installed from AUR(Archlinux), which pulls the source code and compile it, so technically, I have already complied it with libmtp-zune installed. I'll recompile the GTK2 version and see, because it also freezes sometimes.

I'm using mtpfs now to send files directly to a mounted partition.

**Comment by 0rAX0** [comment]
And here's the error I get if I try to download files(connectz is an alias for mtp-connect): 

connectz --getfile Tilawat\ Muhammad\ Imran.alb ~/Downloads/1.alb
Your system does not appear to have UTF-8 enabled ($LANG="en_US.utf8")
If you want to have support for diacritics and Unicode characters,
please switch your locale to an UTF-8 locale, e.g. "en_US.UTF-8".
libmtp version: 1.1.2

libusb couldn't open USB device /dev/bus/usb/001/002: Permission denied.
libusb requires write access to USB device nodes.
libusb couldn't open USB device /dev/bus/usb/005/002: Permission denied.
libusb requires write access to USB device nodes.
libusb couldn't open USB device /dev/bus/usb/005/003: Permission denied.
libusb requires write access to USB device nodes.
Device 0 (VID=045e and PID=0710) is a Microsoft Zune.
MTPZ device detected. Authenticating...
(MTPZ) Setting session initiator info: success.
(MTPZ) Resetting handshake: success.
(MTPZ) Sending application certificate message: success.
(MTPZ) Getting and validating handshake response: success.
(MTPZ) Sending confirmation message: success.
(MTPZ) Opening secure sync session: success.
Get file Tilawat Muhammad Imran.alb
Getting Tilawat Muhammad Imran.alb to /home/rax/Downloads/1.alb
Progress: 16 of 16 (100%)
Error getting file from MTP device.
Error 2: PTP Layer error 02fe: LIBMTP_Get_File_To_File_Descriptor(): Could not get file from device.
Error 2: (Look this up in ptp.h for an explanation.)
Unknown options: /home/rax/Downloads/1.alb

**Comment by kbhomes** [comment]
Hm, you're properly running `make` and `make install`, correct? I suppose what you can do to confirm whether or not it has linked with my libmtp changes is to run gMTP from a terminal. This way, you can expect to see the libmtp messages and hopefully the (MTPZ) messages. 

If that doesn't work, it might be possible to run `ldd /usr/local/bin/gmtp` (or whatever path your gMTP executable is located) and determine the location of the libmtp.so.\* it is linking with. For the code in this libmtp-zune repository, it should be building a libmtp.so.9. Once you note the location, make sure that `make install` is installing the library to this location.

Regarding the error with `mtp-connect`, I believe the issue stems from libmtp not knowing where to download "Tilawat Muhammad Imran.alb" from. For example, I believe that the .alb files (which have no content) are located in "/Albums/" on the device. Moreover, however (and I just realized this from running the `mtp-getfile` example), the program expects the argument to be the `fileid` or `trackid` of the desired file, not its name. These IDs can be found using `mtp-files`. For example, my device has "The Killers--Hot Fuss.alb" with an ID of 100663378, and so the proper usage of the program is `mtp-getfile 100663378 "~/Music/The Killers--Hot Fuss.alb"`.

**Comment by kbhomes** [comment]
I should mention that download the .alb files seem to be unsupported and returns an error, seemingly because they are abstract objects and not real files.

**Comment by 0rAX0** [comment]
Yes, I forgot to add a prefix to install to /usr, everything is working fine now. Thank you.

And thanks for the explanation too. :)

**Comment by theleestarr** [comment]
Unable to pull file from Zune:

Error getting file from MTP device.
Error 2: PTP Layer error 02fe: LIBMTP_Get_File_To_File_Descriptor(): Could not get file from device.
Error 2: Error 02fe: PTP: Protocol error, data expected

(gmtp:3600): Gtk-CRITICAL **: gtk_widget_hide: assertion 'GTK_IS_WIDGET (widget)' failed

(gmtp:3600): Gtk-CRITICAL **: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed
Segmentation fault
